services:
  ollama:
    build: .
    container_name: ollama-docker
    volumes:
      - .:/root/.ollama
#    ports:
#      - "11434:11434"
    tty: true
    stdin_open: true
    entrypoint: bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]